# Generated by Django 5.2.8 on 2025-11-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0003_alter_vote_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('profile',)},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
    ]
