# Generated by Django 5.2.8 on 2025-11-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0004_alter_vote_unique_together_remove_vote_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
