# Generated by Django 5.2.8 on 2025-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0005_candidate_is_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_connected',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
