# Generated by Django 5.2.8 on 2025-11-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0006_remove_candidate_is_connected_profile_is_connected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cycle',
        ),
        migrations.AddField(
            model_name='profile',
            name='cycle',
            field=models.CharField(choices=[('bts', 'BTS'), ('licence', 'Licence'), ('master', 'Master'), ('ingenieur', 'Ingénieur')], default='bts', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='niveau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
