# Generated by Django 5.2.8 on 2025-11-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0007_alter_profile_options_remove_profile_filiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cycle',
            field=models.CharField(default='bts', max_length=100),
        ),
    ]
