# Generated by Django 5.2.8 on 2025-11-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matricule',
            field=models.CharField(default='MAT', max_length=100),
        ),
    ]
