# Generated by Django 5.2.8 on 2025-11-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0008_alter_candidate_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cycle',
            field=models.CharField(choices=[('bts', 'BTS'), ('licence', 'Licence'), ('master', 'Master'), ('ingenieur', 'Ingénieur')], default='bts', max_length=100),
        ),
    ]
