# Generated by Django 5.2.8 on 2025-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0009_alter_candidate_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo_url',
            field=models.ImageField(blank=True, help_text='Format recommandé: 300x300px, max 2MB', max_length=500, null=True, upload_to='candidats/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Format recommandé: 300x300px, max 2MB', max_length=500, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recu',
            field=models.ImageField(blank=True, help_text='Format recommandé: 300x300px, max 2MB', max_length=500, null=True, upload_to='recus/'),
        ),
    ]
