# Generated by Django 5.2.8 on 2025-11-21 09:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0010_alter_candidate_photo_url_alter_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
