# Generated by Django 5.2.8 on 2025-11-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0012_alter_profile_photo_alter_profile_recu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='niveau',
            field=models.IntegerField(blank=True, max_length=5),
        ),
    ]
