# Generated by Django 5.2.8 on 2025-11-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0013_alter_profile_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='niveau',
            field=models.IntegerField(blank=True),
        ),
    ]
