# Generated by Django 5.2.8 on 2025-11-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0014_alter_profile_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bureau_color',
            field=models.CharField(default='#3498db', max_length=7, verbose_name='Couleur du Bureau'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='bureau_name',
            field=models.CharField(default='Bureau Exécutif', max_length=100, verbose_name='Nom du Bureau'),
        ),
    ]
