# Generated by Django 5.2.8 on 2025-11-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0015_candidate_bureau_color_candidate_bureau_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
