# Generated by Django 5.2.8 on 2025-11-22 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0016_profile_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_connected',
        ),
        migrations.AddField(
            model_name='profile',
            name='session_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
