# Generated by Django 5.2.8 on 2025-11-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0017_remove_profile_is_connected_profile_session_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
