# Generated by Django 5.2.8 on 2025-11-22 15:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0018_profile_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='programme_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fichier PDF'),
        ),
    ]
