# Generated by Django 5.2.8 on 2025-11-22 17:49

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0021_alter_candidate_programme_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='programme_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='pdf_documents/', verbose_name='Fichier PDF'),
        ),
    ]
