# Generated by Django 5.2.8 on 2025-11-22 19:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0022_alter_candidate_programme_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='programme_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Programme électoral (PDF)'),
        ),
    ]
