# Generated by Django 5.2.8 on 2025-11-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0023_alter_candidate_programme_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='campus',
            field=models.CharField(default='Bonamoussadi', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bureau_name',
            field=models.CharField(default='Bureau', max_length=100, verbose_name='Nom du Bureau'),
        ),
    ]
