# Generated by Django 5.2.8 on 2025-11-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0024_profile_campus_alter_candidate_bureau_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='campus',
            field=models.CharField(default='Bonamoussadi', max_length=100),
        ),
    ]
