# Generated by Django 5.2.8 on 2025-11-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0025_candidate_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cycle',
            field=models.CharField(choices=[('bts', 'BTS'), ('hnd', 'HND'), ('licence', 'Licence'), ('bachelor', 'Bachelor of Technology'), ('master', 'Master'), ('ingenieur', 'Ingénieur')], default='bts', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cycle',
            field=models.CharField(choices=[('bts', 'BTS'), ('hnd', 'HND'), ('licence', 'Licence'), ('bachelor', 'Bachelor of Technology'), ('master', 'Master'), ('ingenieur', 'Ingénieur')], default='bts', max_length=100),
        ),
    ]
