# Generated by Django 5.2.8 on 2025-11-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0026_alter_candidate_cycle_alter_profile_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cycle',
            field=models.CharField(choices=[('bts', 'BTS'), ('hnd', 'HND'), ('lipro', 'Licence Professionnelle'), ('litech', 'Licence de Technologie'), ('bachelor', 'Bachelor of Technology'), ('master', 'Master'), ('ingenieur', 'Ingénieur')], default='bts', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cycle',
            field=models.CharField(choices=[('bts', 'BTS'), ('hnd', 'HND'), ('lipro', 'Licence Professionnelle'), ('litech', 'Licence de Technologie'), ('bachelor', 'Bachelor of Technology'), ('master', 'Master'), ('ingenieur', 'Ingénieur')], default='bts', max_length=100),
        ),
    ]
